xcode:
  company: Rosberry
font:
  extensionFolderPath: ./Classes/Presentation/Extensions
  extensionFontPath: ./Classes/Presentation/Extensions/UIFonts+App.swift
  commonTemplatePath: ./.templates/common
  commandTemplatePath: ./.templates
  fontsFolderPath: ./Resources/Fonts
  fontsTemplatePath: ./.templates/rsb_fonts
  infoFontName: UIAppFonts
  fontTemplateName: UIFonts+App.stencil
outputs:
- templateName: rsb_mvp_vm_module
  path: Classes/Presentation/Modules
- templateName: rsb_mvp_vm_list_module
  path: Classes/Presentation/Modules
- templateName: rsb_generic_list_module
  path: Classes/Presentation/Modules
- templateName: rsb_generic_module
  path: Classes/Presentation/Modules
- templateName: rsb_service
  path: Classes/BusinessLogic/Services
services:
  servicesPath: ./Classes/BusinessLogic/Services/Services.swift
  serviceMark: '{{name | upperFirstLetter}}'
  serviceMarkName: '{{name | lowerFirstLetter}}'
  serviceMarkHas: '{% if isNewFile %}Has{{name | upperFirstLetter}}Service{% else %}                       Has{{name | upperFirstLetter}}Service{% endif %}'
